### PR TITLE
Use the request's url as operation name for Span objects.

### PR DESCRIPTION
**Pull request by carlosalberto**

### CODE REVIEW

**Comment by pavolloffay** [comment]
Link to the general discussion opentracing-contrib/meta#25 , related to #12

**Comment by pavolloffay** [comment]
@tedsuo can this be closed?

**Comment by yurishkuro** [comment]
Closing - this is not a good change, as discussed many times, because it introduces potentially high cardinality as operation name

**Comment by tedsuo** [comment]
👍

**Pull request closed without merging**
